steps:
- name: 'hashicorp/terraform:1.7.5'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform apply -auto-approve
  dir: 'terraform'

# Optionally, define substitutions for your project ID
substitutions:
  _PROJECT_ID: dealofday-398415
